# Overview {.unnumbered}
The Mycological Curriculum for Education and Discovery [MycoEd](https://mycocosm.jgi.doe.gov/mycocosm/home/myco-ed) is a **Course-Based Undergraduate Research Experience (CURE)** that features team-based, hands-on experiments in fungal biology and genomics. You will learn new laboratory techniques and data analysis by starting with sample collection, fungal isolation, and the characterization of the resulting data to improve fungal genomic resources. Genomic DNA will be extracted from samples for genome sequencing, assembly, and annotation. By isolating and sequencing new fungal species, your team will help produce high-quality fungal reference genomes. This course will prepare you with workforce training in fungal biology and genomics and empower you to be a contributor to fungal genomics! Importantly, you will practice lab and bioinformatics skills that are broadly applicable!

To learn more about Quarto books visit [Quarto Books](https://quarto.org/docs/books)
To learn more about the MycoEd curriculum visit the [MycoEd](https://mycocosm.jgi.doe.gov/mycocosm/home/myco-ed))

## Course Outcomes
* **CO1**: **Isolate** fungal endophytes,
* **CO2**: **Characterize** the morphology of fungal cultures through phenotypic and genomic assays,
* **CO3**: **Practice** extracting fungal DNA,
* **CO4**: **Describe** the process to PCR amplify fungal ITS,
* **CO5**: **Formulate** meaningful and testable scientific questions/hypotheses,
* **CO6**: **Collect** and **critically interpret** experimental data (including metadata),
* **CO7**: **Maintain** an appropriate laboratory notebook,
* **CO8**: **Summarize** their work and **describe** their findings in written and oral presentations.
* **CO9**: **Apply** evidence-based strategies to improve scientific collaboration and teamwork skills.
* **CO10**: **Reflect** on your development as a scientist and team member through structured prompts and reflections.


## Module Slides
The links below open the RevealJS slide decks for each module. Please note the slides can be advanced using the arrow keys on your keyboard, and you can also use the menu in the bottom right corner to navigate between slides. The slide decks are designed to be used in conjunction with the corresponding module content in this book, so feel free to refer back to them as needed while working through the modules.    

::: {.callout-tip}
Links to RevealJS slide decks for each module are listed below.

* [Open Module 0 RevealJS Slides](module0-slides.html)
* [Open Module 1 RevealJS Slides](module1-slides.html)
* [Open Module 2 RevealJS Slides](module2-slides.html)
* [Open Module 3 RevealJS Slides](module3-slides.html)
* [Open Module 4 RevealJS Slides](module4-slides.html)
* [Open Module 5 RevealJS Slides](module5-slides.html)
* [Open Module 6 RevealJS Slides](module6-slides.html)
* [Open Module 7 RevealJS Slides](module7-slides.html)
:::