# Module 5: Tissue Preparation

## Module 5.1 – Tissue Preparation for Genome Sequencing

### Instructor Laboratory Preparation Instructions

**Materials and Equipment:**
- Autoclave
- Laminar Flow Hood (if available)
- Cellophane
- 100x15mm Petri Dishes
- 60x15mm Petri Dishes
- Agar, Bacteriological
- Potato Dextrose Agar
- Alcohol Lamp or Bunsen Burner
- Forceps
- Scalpel (make sure the handle is metal, as it will be flame sterilized and plastic will melt)

**Sterility:**
If you don't have a laminar flow hood, you may create a similar environment by setting up 2 torches over your work space. First, clean your work area with bleach, and/or ethanol. Set the torches facing each other with enough space to work underneath. Light the torches and pour media into plates under the flames.

**Potato Dextrose Agar (PDA) Plates:**
Fungi cultured from leaves on water agar are transferred to nutrient Potato Dextrose Agar (PDA) plates. We use one 60x15 mm Petri dish for each fungal isolate.

**Potato Dextrose Agar Recipe:**
Suspend 39 grams Agar, Bacteriological in 1000 ml (1 L) distilled water. Heat to boiling to dissolve the medium completely (in most cases, this step can be skipped as autoclaving will dissolve media). Sterilize by autoclaving at 15 lbs pressure (121°C) for 15 minutes.

When the media is cool enough to handle with autoclave gloves, pour 60x15mm plates in a sterile environment. Do not let it cool too long as the media will solidify. Each 60x15mm plate holds approximately 8 ml media. If plates will be used immediately smaller amounts of media can be poured into plates. If plates will be stored, use larger amounts. Store plates in the original Petri dish sleeve in the refrigerator (~4 °C) until use.

**Cellophane Plates:**
Fungal tissue can be harvested from cellophane plates. Cut cellophane discs slightly smaller than the Petri dish so that they lay flat on the PDA media. Using the bottom of the Petri dish as a template, draw a circle on the cellophane and the cut out discs on the inside of the line.

Place cellophane discs into an autoclavable container with water. Place each cellophane disc individually into the water and try to stagger them in the water. This staggering step ensures that you can more easily remove the discs from the water. Cover your container with foil and sterilize by autoclaving at 15 lbs pressure (121°C) for 15 minutes.

Working in your sterile environment, place one cellophane disc onto cooled PDA agar in 60x15mm plates. Use sterile forceps to transfer each cellophane disc onto the PDA plate. If you can't easily remove single discs, try the "slide" technique. Dip your forceps into the container with the discs until you touch a disc. Using the forceps as a probe (not pinched) slide the disc to the side of the container and up the side of the container. Often, you'll pull out one disc. Sometimes more than one disc will slide up, but it's usually easy to see the individual discs at this point. You can then use your forceps to pull out one disc. If you grasp one disc with your forceps, you can swirl it in the water in the container to dislodge any other discs that might be attached. Open the lid of the Petri dish and lay the cellophane onto the solid agar.

## Module 5.2 – Tissue Preparation for Genome Sequencing

### Purpose
This protocol guides you through the culturing and harvesting of fungal tissue for molecular applications.

### Introduction
The long-term goal of this endophyte isolation project is to develop a robust dataset of fungal genomes. We are piloting this project in our course to determine if whole genome extractions are possible using home laboratory techniques. If successful, the project will be expanded in several directions. Any data generated from this project will be made available on the Mycocosm Web Portal. These data can then be used by students and researchers to analyze fungal genomes. Beyond phylogenetic inferences and evolutionary reconstructions, a variety of research questions can be addressed using fungal genomic data. Genomic data can elucidate the functions of these fungi and contribute to an understanding of their biology. In addition, if this pilot project is successful, future studies will incorporate stress factors, such as salts, metals, or temperatures, to understand the morphological, physiological and genetic responses of fungi to environmental stressors.

This pilot project is being conducted in collaboration with mycologists and mycology students across North America. In addition to Oregon State University, students from the University of Colorado, both Denver and Boulder, Denver Botanic Gardens, Colorado State University, and Duke University, are collecting tissue and isolating fungal endophytes from plant hosts. Genomic data will be generated by the Joint Genome Institute. This is the first project of its kind and the most comprehensive project investigating endophytes on a large geographic and taxonomic scale.

To prepare your fungal tissue for full genome sequencing, you will transfer some mycelia to a Petri dish with cellophane.

Once fungal endophytes have been cultured from host plants, these fungal cultures will be identified using ITS (the fungal barcode region) sequencing. The ITS sequence will provide some level of taxonomic placement of your isolate, perhaps even to species. This ITS identification step also allows the determination of which fungal cultures to submit for full genome sequencing.

### Sub-Culturing on Cellophane
1. Clean your workspace as described previously. Work under flames or in a laminar flow hood if available.
2. Label your Cellophane lined Petri Dish appropriately.
3. Sterilize implements (forceps and scalpel).
4. Scrape mycelia from PDA plates that you have been growing. Be sure to avoid transferring any media as much as possible.
   a. Leaving the assay plate on the bench space, remove the parafilm of the inoculation plate and slightly crack open the lid using your non-dominant hand.
   b. Insert your forceps into the crack of the Petri dish and attempt to sample some mycelium.
      i. If you are unable to remove mycelia with your forceps, use your scalpel to remove mycelia with the least amount of agar possible.
5. Transfer the mycelia to a Petri dish with cellophane.
   a. Carefully remove the chunk of agar. Replace the lid. Slide the sample plate away. Slide a cellophane plate towards you.
   b. Crack open the cellophane plate using your non-dominant hand, and carefully insert the forceps with the agar and mycelium.
   c. To deposit the agar onto the PDA agar, submerge the forceps into the agar on the plate. This should force the agar and mycelium from your forceps, onto the PDA agar.
   d. Pull your forceps straight out to leave the agar and mycelium on the plate.
   e. The mycelia will be sticky, so you might need to scrape it off using sterile implements. If you're using forceps to transfer, use the sterilized scalpel to scrape mycelia off the forceps onto cellophane in the Petri dish.
6. Seal Petri dish with parafilm.
7. Allow fungi to fill the cellophane.
8. Repeat this process with all fungal isolates that will be sent for genome sequencing.

### Harvesting Mycelia for Genome Sequencing Instructions
Full genome sequencing requires large amounts of tissue to be successful. The tissue grown on the cellophane plates will be harvested, dried, and sent for genome sequencing.

### Student Lab Supplies
- 1.5 ml Eppendorf tubes
- Sharpie
- Scalpel
- Forceps
- Silica
- Probe

### Overview
The goal of this supplement is to prepare fungal tissue for DNA extraction and sequencing. The cellophane overlay method was implemented to obtain pure tissue conducive to clean DNA extractions (Fig. 1).

Figure 1 - Using aseptic techniques (step 1), prepare agar plates and arrange a sterile location for transfer. Add one disk of sterile cellophane to each plate (step 2) and inoculate with the fungal isolate, avoiding the transfer of residual agar, in the center of the disk (step 3). Allow the fungus to grow on top of the cellophane in a dark incubator at 26°C(step 4). Take the initial weight of the empty Eppendorf tube. After the cellophane disk is covered, peel the tissue to remove it and place it in the empty Eppendorf tube. Place the open tube in a jar with silica gel in the bottom. Cover the jar. Allow the tissue to dry for 4-7 days (step 5). Once the tissue is dry, close the tube and take the final weight. 1-2 grams of tissue should be recovered. Store the sample in a clean place. It is now ready for in-house DNA extraction or shipping. Figure created in BioRender. Knight, C. (2025) https://BioRender.com/s61a377

### Instructions
1. You will be harvesting fungal tissue from the cellophane PDA petri dishes.
2. Use a laminar flow hood or set up flames to create a sterile environment. Clean your sterile area.
3. Light your flame source. Dip your harvesting implement(s) (scalpel, forceps, and/or probe) into alcohol. Flame your implements and let it cool.
4. Once cool, open your petri dish lid, and lay this facing upward on your workspace. Remove fungal tissue by scraping from cellophane. In some cases, the entire fungal tissue will easily peel from the cellophane. In some cases, the mycelia will be stuck to the cellophane. In this case, you will need to use some combination of instruments to remove the fungi from the cellophane (Figs 2 and 3, Videos 1 and 2).
5. Place Eppendorf tubes into a jar filled with silica. The silica will allow you to stand up the tubes in the jar. Keep the lids of the Eppendorf tubes open to allow the tissue to dry.
6. Seal silica-filled jar with the lid. Allow the tissue to dry for 5-10 days.
7. Once the tissue is dry, remove the Eppendorf tubes from the silica jar and close the lids.
8. Proceed to the Sample submission module.