# Summary {.unnumbered}

This workbook outlines the  Myco-Ed curriculum for BSC 495: The Hidden World's Code. Students will gain hands-on experience in fungal biology and genomics, from sample collection and fungal isolation through DNA sequencing. By the end of the course, students scholars will have contributed to high-quality fungal reference genomes and developed broadly applicable skills in lab techniques and bioinformatics. More information and course resources are available at the [BSC495-HWC GitHub organization](https://github.com/BSC495-HWC).

But wait... there is more: genome assembly, and annotation. We hope you continue working on your isolates and share your results with us and the scientific community! One possibility is a *microPublication*. We are here to support you in your continued work on your isolates, and we would love to hear about your progress. Please feel free to reach out to us with any questions or updates on your work. We look forward to seeing the amazing things you will accomplish with your fungal isolates!
